### ISSUE TITLE
 The value object (Python class sklearn_pandas.transformers.CategoricalImputer) is not a supported Transformer

### ISSUE THREAD

**Issue by ZimengChen** [scikit-learn-contrib/sklearn-pandas#193] opened 2019-01-29 02:28 UTC
I try using CategoricalImputer to fill NaN values in data with the strategy 'constant':

```
all_tuple_list = [    
    (['edu'], [CategoricalImputer(strategy='constant',fill_value='-1'),LabelBinarizer()]),
    (['marital'], [CategoricalImputer(strategy='constant',fill_value='-1'),LabelBinarizer()]),
    (['profession'], [CategoricalImputer(strategy='constant',fill_value='-1'),LabelBinarizer()]),
    (['relation1'], [CategoricalImputer(strategy='constant',fill_value='-1'),LabelBinarizer()]),
    (['relation2'], [CategoricalImputer(strategy='constant',fill_value='-1'),LabelBinarizer()]),
]

mapper = DataFrameMapper(all_tuple_list,df_out=True)

lgb = LGBMClassifier(learning_rate=0.2,n_jobs=4,silent=True,metrics='auc',is_unbalance=True,n_estimators=1000)

pipeline = PMMLPipeline([("mapper",mapper),("classifier",lgb)])

pipeline.fit(X=train_x,y=train_y,
             **fit_params)

sklearn2pmml(pipeline, "D:\\WORK\\thirdData\\model\\cash_gbm.pmml",with_repr=True,java_encoding='gbk')
```

Then error:

```
Standard output is empty
Standard error:
一月 29, 2019 10:17:51 上午 org.jpmml.sklearn.Main run
信息: Parsing PKL..
一月 29, 2019 10:17:51 上午 org.jpmml.sklearn.Main run
信息: Parsed PKL in 113 ms.
一月 29, 2019 10:17:51 上午 org.jpmml.sklearn.Main run
信息: Converting..
一月 29, 2019 10:17:51 上午 org.jpmml.sklearn.Main run
严重: Failed to convert
java.lang.IllegalArgumentException: The value object (Python class sklearn_pandas.transformers.CategoricalImputer) is not a supported Transformer
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:616)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:72)
	at sklearn.Initializer.encodeFeatures(Initializer.java:41)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:202)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.Transformer
	at java.lang.Class.cast(Unknown Source)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:41)
	... 8 more

Exception in thread "main" java.lang.IllegalArgumentException: The value object (Python class sklearn_pandas.transformers.CategoricalImputer) is not a supported Transformer
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:616)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:72)
	at sklearn.Initializer.encodeFeatures(Initializer.java:41)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:202)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.Transformer
	at java.lang.Class.cast(Unknown Source)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:41)
	... 8 more

```

**Comment by vruusmann** [comment] 2019-01-29 07:31
This issue is a duplicate of https://github.com/jpmml/sklearn2pmml/issues/128

In brief, the `CategoricalImputer` transformer class has been moved from `sklearn_pandas.categorical_imputer` module to `sklearn_pandas.transformers` module between SkLearn-Pandas package versions 1.7 and 1.8. You have an old SkLearn2PMML package version installed, which does not know about this "migration" yet.

The fix is simple - update the SkLearn2PMML package version to the latest 0.41.0 (available in PyPI).

**Closed** 2020-11-08 07:32 UTC
